### ISSUE TITLE
Karyon2 governator boostrapping feature out of sync with maven repo

### ISSUE THREAD

**Issue by venkatraghavang** [Netflix/karyon#181]
2.2.0-ALPHA3 version on central maven contains the 1.3.0's Karyon class although the class description says about Bootstrapping. netflix.karyon.Karyon contains the following: 

KaryonServer forApplication(Class<?> mainClass, LifecycleInjectorBuilderSuite... suites) 
instead of 
public static KaryonServer forApplication(Class<?> mainClass, BootstrapModule... bootstrapModules)

Central maven needs to be updated with correct version of Karyon2-governator.

**Comment by NiteshKant** [comment]
@venkatraghavang looks like the last release 2.2.0-ALPHA6 was not published to maven central and that is the reason the latest governator related code changes are not present in the artifact.
I will release the next version.

**Comment by venkatraghavang** [comment]
Great! Thanks. looking forward to it.

**Comment by NiteshKant** [comment]
2.2.00-ALPHA7 depends on the latest governator artifacts.
