### ISSUE TITLE
Nasty problem in blocking Jersey

### ISSUE THREAD

**Issue by maksimlikharev** [Netflix/karyon#198]
HttpContentInputStream used in the netty bridge contains bug that results in partial or missing payload passed to Jersey.
Reimplemented  InputStream to Observable adapter, will provide pull request if you interested.

**Comment by NiteshKant** [comment]
Thanks for reporting the issue. Yes, it will be great if you have a fix for this.

**Comment by maksimlikharev** [comment]
done, pull request produced

**Comment by NiteshKant** [comment]
This was fixed via #209 Thanks @maksimlikharev !
