### ISSUE TITLE
Update eureka-client version in karyon2-eureka for ribbon 2.0

### ISSUE THREAD

**Issue by schmitch** [Netflix/karyon#214]
Hello, currently karyon2-eureka uses a older eureka-client which pulls in:
- ribbon-core:2.0-RC9
- ribbon-httpclient:2.0-RC9
- ribbon-loadbalancer:2.0-RC9

It would be good to upgrade to eureka 1.1.151 so that the projects could use ribbon 2.0 and not the release canidate.

**Comment by NiteshKant** [comment]
Sure, you want to send a PR?

**Comment by schmitch** [comment]
Yeah, sure, done ;)
