### ISSUE TITLE
Question: How would you prefer a Jersey 2.X support PR done?

### ISSUE THREAD

**Issue by Helmsdown** [Netflix/karyon#257]
I am interested in working on getting karyon to support Jersey 2.X. 

A few questions would help guide my efforts:

1. Do you want to continue supporting Jersey 1.X?
2. If so, would you want to handle jersey 2.x support in a new gradle module? (this would allow people to avoid having jersey 1.x jars on their classpath if they are using jersey 2.x)
3. If yes to to the above question, and there happens to be sharable code between the jersey 1.x module and the jersey 2.x module would you prefer to "clone-and-own" between the modules or create a common module that both depend on?

Thanks!

**Comment by elandau** [comment]
Are you interested in just using Jersey 2.x in Karyon framework or a using Jersey 2.x with RxNetty?

**Comment by Helmsdown** [comment]
I am interested in writing my Rest endpoints in Jersey 2.x and using Karyon as my base server (so later I can take advantage of other Netflix OSS components).
