### ISSUE TITLE
More compact configuration format

### ISSUE THREAD

**Issue by elandau** [Netflix/karyon#331]
Archaius2 defaults to using only properties files to specify configuration.  We should look into more readable formats such as HOCON or YAML.  We may also consider a custom format that makes it possible to specify 'conditional' blocks.  For example,

```
- foo: [env=="local"]
    prop: value_for_local

- foo: [env=="cloud"]
    prop: value_for_cloud
}
```

**Comment by jhspaybar** [comment]
Creating yet another configuration format feels like a really bad idea to me.  Are there things that aren't possible with our current format and usage of Archaius, etc?

**Comment by elandau** [comment]
3.x branch no longer under development
