### ISSUE TITLE
Karyon 3.0 should be used or not?

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/karyon#341]
Hello everyone!

I'm new to NetflixOSS, i'm using some modules and used a few with spring, but wanna know they better using only the Netflix stack, but i'm facing a doubt, reading the karyon 2 and 3 readme it got me confused:

In 2.0 its saying:

```
Karyon 2.0 is no longer supported. ...
```

and in 3.0:
```
After much discussion we have decided to backport the majority of DI related functionality from Karyon back in to governator. 
This was done to avoid confusion regarding already duplicated classes and simplify adoption since governator is already a dependency of all internal Netflix projects. 
The sub-projects of karyon3 will be merged with their respective OSS projects (ex. eureka-governator). 
Overall we expect the experience to stay the same but some class names and packages will end up being renamed. We appologize for any inconvience they may cause early adopters of Karyon3.
```

Long story short, should i use karyon to bootstrap the Netflix stack or use only governator?

**Comment by elandau** [comment]
Yes, you should be using governator to bootstrap your application.  Most of our OSS projects already provide governator/guice modules that you can use in your project.  Here are a few,

Eureka,
https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/guice/EurekaModule.java

Archaius,
https://github.com/Netflix/archaius/tree/2.x/archaius2-guice

**Comment by kennedyoliveira** [comment]
@elandau, thank you for clarifying that.

Another doubt, i noticed the EurekaModule is for configuring the client, exist something that i can start a Eureka Server in my application, like embedded, similar to what springboot do with @EnableEureka?

I'm asking because i used the eureka server with springboot and it's very convenient because of the possibility of creating different profiles to work in different environments, and reading the eureka documentation i understood that i should configure the deploy and start it to get a server working. 

I wanna understand all the Netflix stack and wire them together without spring, and i didn't saw an effective way of starting the server.

**Comment by jaume-pinyol** [comment]
I don't know about an embedded one but you can use: 
https://github.com/Netflix-Skunkworks/zerotodocker

and start eureka in a docker container.

About the environment you can get that using the archaius property -Ddeployment.environment=dev|pre|prod|...
and then having different property files like: 
* your-app-dev.properties
* your-app-prod.properties
* etc
Archaius will load the property file depending on the environment

**Comment by kennedyoliveira** [comment]
@jaume-pinyol, thank you for your suggestion, it sure will do the trick.
I forgot about the archaius property, need to use it more :D
I think that maybe it should be added to the wiki in eureka, maybe it helps someone with that doubt.
